title: "ギャルゲーのボイスキープ化メモ"
description: "ギャルゲーをボイスキープにする方法とパッチを、ゲーム名から探せます。"
lang: "ja"
url: "https://cjangcjengh.github.io"
baseurl: "/galgame-voice-keep"
repository: "CjangCjengh/galgame-voice-keep"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
